language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t slavsquat/docker-udemy -f Dockerfile.dev .

script:
    - docker run -e CI=true slavsquat/docker-udemy npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-udemy"
    env: "DockerUdemy-env"
    bucket-name: "elasticbeanstalk-us-east-2-857936270324"
    bucket-path: "docker-udemy" # initially equal to app
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY