language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t slavsquat/docker-udemy -f Dockerfile.dev .

script:
    - docker run -e CI=true slavsquat/docker-udemy npm run test